name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
      name: Checkout Code
      runs-on: ubuntu-latest

      steps:

        - name: Checkout Code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          run: npm run test:local
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs

